// lib/curriculum.ts — Canonical Fall 2026 Curriculum Definitions

export interface SessionInfo {
  id: string
  weekNumber: number
  level: 'BEGINNER' | 'LEVEL_2'
  dayOfWeek: string
  date: string // ISO date string '2026-10-08'
  dateFormatted: string // 'Oct 8, 2026 (Thu)'
  startTime: string
  endTime: string
  timeLabel: string
  title: string
  moduleName?: string
  concept: string
  project: string
  requiresPrerequisite: boolean
  pricePerUnit: number
}

export const FALL_BEGINNER_SESSIONS: SessionInfo[] = [
  {
    id: 'fall-2026-beg-1',
    weekNumber: 1,
    level: 'BEGINNER',
    dayOfWeek: 'Thursday',
    date: '2026-10-08',
    dateFormatted: 'Oct 8, 2026 (Thu)',
    startTime: '17:00',
    endTime: '18:00',
    timeLabel: '5:00 PM – 6:00 PM',
    title: 'Scratch & Coding Foundations',
    concept: 'Introduction to visual block coding, sprites, motion loops, and X/Y coordinates.',
    project: 'Build an interactive animated maze game.',
    requiresPrerequisite: false,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-beg-2',
    weekNumber: 2,
    level: 'BEGINNER',
    dayOfWeek: 'Thursday',
    date: '2026-10-15',
    dateFormatted: 'Oct 15, 2026 (Thu)',
    startTime: '17:00',
    endTime: '18:00',
    timeLabel: '5:00 PM – 6:00 PM',
    title: 'Interactive Game & Animation',
    concept: 'Sprite collision detection, keypress event triggers, and costume animations.',
    project: 'Create a multi-character arcade dodge game.',
    requiresPrerequisite: false,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-beg-3',
    weekNumber: 3,
    level: 'BEGINNER',
    dayOfWeek: 'Thursday',
    date: '2026-10-22',
    dateFormatted: 'Oct 22, 2026 (Thu)',
    startTime: '17:00',
    endTime: '18:00',
    timeLabel: '5:00 PM – 6:00 PM',
    title: 'Logic, Loops & Scoreboards',
    concept: 'Conditional logic (if/then statements), score variables, and win/loss states.',
    project: 'Design a space coin catcher with dynamic scoreboards.',
    requiresPrerequisite: false,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-beg-4',
    weekNumber: 4,
    level: 'BEGINNER',
    dayOfWeek: 'Thursday',
    date: '2026-10-29',
    dateFormatted: 'Oct 29, 2026 (Thu)',
    startTime: '17:00',
    endTime: '18:00',
    timeLabel: '5:00 PM – 6:00 PM',
    title: 'Custom Blocks & Sound FX',
    concept: 'Reusable My Blocks functions, sound synthesis, and backdrop stage transitions.',
    project: 'Build a multi-level platformer stage with sound effects.',
    requiresPrerequisite: false,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-beg-5',
    weekNumber: 5,
    level: 'BEGINNER',
    dayOfWeek: 'Thursday',
    date: '2026-11-05',
    dateFormatted: 'Nov 5, 2026 (Thu)',
    startTime: '17:00',
    endTime: '18:00',
    timeLabel: '5:00 PM – 6:00 PM',
    title: 'Multi-Level World Design',
    concept: 'Level switching variables, item collectibles, and health bar mechanics.',
    project: 'Develop a 3-level adventure quest game.',
    requiresPrerequisite: false,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-beg-6',
    weekNumber: 6,
    level: 'BEGINNER',
    dayOfWeek: 'Thursday',
    date: '2026-11-12',
    dateFormatted: 'Nov 12, 2026 (Thu)',
    startTime: '17:00',
    endTime: '18:00',
    timeLabel: '5:00 PM – 6:00 PM',
    title: 'UI Polish & Special Effects',
    concept: 'Screen particle feedback, victory animations, and custom UI design systems.',
    project: 'Add popping particle counters and animated victory screens to your game.',
    requiresPrerequisite: false,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-beg-7',
    weekNumber: 7,
    level: 'BEGINNER',
    dayOfWeek: 'Thursday',
    date: '2026-11-19',
    dateFormatted: 'Nov 19, 2026 (Thu)',
    startTime: '17:00',
    endTime: '18:00',
    timeLabel: '5:00 PM – 6:00 PM',
    title: 'Beginner Capstone Showcase',
    concept: 'Final code triage, debugging strategies, and peer review presentation.',
    project: 'Present your completed game at the Studio Showcase & Peer Review Session.',
    requiresPrerequisite: false,
    pricePerUnit: 28.57,
  },
]

export const FALL_LEVEL_2_SESSIONS: SessionInfo[] = [
  {
    id: 'fall-2026-lvl2-1',
    weekNumber: 1,
    level: 'LEVEL_2',
    dayOfWeek: 'Thursday',
    date: '2026-10-08',
    dateFormatted: 'Oct 8, 2026 (Thu)',
    startTime: '19:00',
    endTime: '20:00',
    timeLabel: '7:00 PM – 8:00 PM',
    title: 'Advanced Physics & Gravity Engines',
    moduleName: 'Module 1: System-Driven Game Mechanics',
    concept: 'Moving beyond basic change y loops into velocity-based systems.',
    project: 'Build a Flappy Bird clone or Doodle Jump mechanics engine featuring elastic bouncing platforms.',
    requiresPrerequisite: true,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-lvl2-2',
    weekNumber: 2,
    level: 'LEVEL_2',
    dayOfWeek: 'Thursday',
    date: '2026-10-15',
    dateFormatted: 'Oct 15, 2026 (Thu)',
    startTime: '19:00',
    endTime: '20:00',
    timeLabel: '7:00 PM – 8:00 PM',
    title: 'Advanced Event Architecture',
    moduleName: 'Module 1: System-Driven Game Mechanics',
    concept: 'Decoupling code strings so multiple elements instantly react to global system triggers.',
    project: 'Create a Secret Agent Security Gate or a multi-stage boss fight.',
    requiresPrerequisite: true,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-lvl2-3',
    weekNumber: 3,
    level: 'LEVEL_2',
    dayOfWeek: 'Thursday',
    date: '2026-10-22',
    dateFormatted: 'Oct 22, 2026 (Thu)',
    startTime: '19:00',
    endTime: '20:00',
    timeLabel: '7:00 PM – 8:00 PM',
    title: 'Data Streams & Scoreboards',
    moduleName: 'Module 1: System-Driven Game Mechanics',
    concept: 'Local vs. global variables, persistent data tracking, and dynamic list arrays.',
    project: 'Build an arcade-style upgrade shop game tracking coin deductions and multipliers dynamically.',
    requiresPrerequisite: true,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-lvl2-4',
    weekNumber: 4,
    level: 'LEVEL_2',
    dayOfWeek: 'Thursday',
    date: '2026-10-29',
    dateFormatted: 'Oct 29, 2026 (Thu)',
    startTime: '19:00',
    endTime: '20:00',
    timeLabel: '7:00 PM – 8:00 PM',
    title: 'Screen Scrolling & Infinite Maps',
    moduleName: 'Module 2: Complex Game Genres',
    concept: 'Moving the world around the player character instead of moving across a static canvas.',
    project: 'Design a horizontal platformer or a top-down car racing game with dynamic terrain wrapping.',
    requiresPrerequisite: true,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-lvl2-5',
    weekNumber: 5,
    level: 'LEVEL_2',
    dayOfWeek: 'Thursday',
    date: '2026-11-05',
    dateFormatted: 'Nov 5, 2026 (Thu)',
    startTime: '19:00',
    endTime: '20:00',
    timeLabel: '7:00 PM – 8:00 PM',
    title: 'Autonomous AI & Pathfinding',
    moduleName: 'Module 2: Complex Game Genres',
    concept: 'Coding smart enemies that track player targets without using simple glide blocks.',
    project: 'Program autonomous patrol guards and chasing AI enemies.',
    requiresPrerequisite: true,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-lvl2-6',
    weekNumber: 6,
    level: 'LEVEL_2',
    dayOfWeek: 'Thursday',
    date: '2026-11-12',
    dateFormatted: 'Nov 12, 2026 (Thu)',
    startTime: '19:00',
    endTime: '20:00',
    timeLabel: '7:00 PM – 8:00 PM',
    title: 'Code Polish & UI Design Systems',
    moduleName: 'Module 3: Polish, Publishing, and Production',
    concept: 'Designing professional game interfaces, particle effect feedback loops, and volume attenuation.',
    project: 'Integrate slick HUD design, sound mixer controls, and animated transitions.',
    requiresPrerequisite: true,
    pricePerUnit: 28.57,
  },
  {
    id: 'fall-2026-lvl2-7',
    weekNumber: 7,
    level: 'LEVEL_2',
    dayOfWeek: 'Thursday',
    date: '2026-11-19',
    dateFormatted: 'Nov 19, 2026 (Thu)',
    startTime: '19:00',
    endTime: '20:00',
    timeLabel: '7:00 PM – 8:00 PM',
    title: 'Capstone Debugging & Group Playtesting',
    moduleName: 'Module 3: Polish, Publishing, and Production',
    concept: 'Code triage, optimization strategies, identifying memory leaks, and processing user feedback.',
    project: 'Final playtesting exhibition, bug bounty hunt, and code presentation.',
    requiresPrerequisite: true,
    pricePerUnit: 28.57,
  },
]

export const ALL_FALL_SESSIONS: SessionInfo[] = [
  ...FALL_BEGINNER_SESSIONS,
  ...FALL_LEVEL_2_SESSIONS,
]

export function getSessionById(id: string): SessionInfo | undefined {
  return ALL_FALL_SESSIONS.find((s) => s.id === id)
}

export function getSessionByWeekAndLevel(weekNumber: number, isLevel2: boolean): SessionInfo | undefined {
  const list = isLevel2 ? FALL_LEVEL_2_SESSIONS : FALL_BEGINNER_SESSIONS
  return list.find((s) => s.weekNumber === weekNumber)
}
